version: 0.2

env:
  variables:
    PROJECT: github.com/iph/yocal

phases:
  install:
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
      # Can't recursively copy our same directory (we want to move the go files, but not the cf file)
      # so we first put into /tmp/temp then copy to the correct directory.
      - mkdir -p /tmp/temp
      - cp -R  $CODEBUILD_SRC_DIR/* /tmp/temp
      - mkdir -p $CODEBUILD_SRC_DIR/$PROJECT
      # We move to the project dir because go is not properly finding the directory (probably need to upgrade to go 1.11)
      - cp -R /tmp/temp/* $CODEBUILD_SRC_DIR/$PROJECT
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build $PROJECT
      - mv yocal app
      - zip app.zip app
      - aws cloudformation package --template cloudformation/main-app.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - aws cloudformation package --template cloudformation/main-app.yml --s3-bucket $S3_BUCKET --output-template template-canary-export.yml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - yocal
    - template-export.yml
    - template-canary-export.yml
