AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Globals:
  Api:
    BinaryMediaTypes:
      - image~1png
      - image~1jpeg
      - '*~1*'

Parameters:
  AppName:
    Type: String
    Description: Name of App

Resources:
  LambdaTrustRole:
    Type: 'AWS::IAM::Role'
    Description: Creating service role in IAM for AWS Lambda
    Properties:
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole'
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
                Effect: Allow
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../app.zip
      Handler: app
      Runtime: go1.x
      Role: !GetAtt LambdaTrustRole.Arn
      AutoPublishAlias: live
      DeploymentPreference:
        Type: LambdaAllAtOnce
        Hooks:
          PreTraffic: !Ref preTrafficHook
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

  preTrafficHook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../app.zip
      Handler: hook
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "codedeploy:PutLifecycleEventHookExecutionStatus"
                - "lambda:InvokeFunction"
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
                - 'rekognition:*'
              Resource:
                '*'
      Runtime: go1.x
      FunctionName: 'CodeDeployHook_preTrafficHook'
      DeploymentPreference:
        Enabled: false
      Timeout: 30
      Environment:
        Variables:
          NewVersion: !Ref GetHelloWorld.Version
          REGION: !Ref AWS::Region
          API_ENDPOINT: "4n6igpgd86"
